import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import Layout from "@/components/Layout";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const router = useRouter()

  const { data: sessionData } = useSession();

  if (sessionData) {
    void router.push("/todos");
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <h1 className="text-3xl">Please login to use TODO app</h1>
      </Layout>
    </>
  );
};

export default Home;
